service: app-sync-twitter-clone

plugins:
  - serverless-appsync-plugin

custom:
  appsync: ${file(config/sls/appsync-api.yaml)}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
